# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
desc "Push a new beta build to TestFlight"
lane :beta do
  gym(
    export_method: "ad-hoc", #打包的方式, development/adhoc/enterprise/appstore
    output_directory: './fastlane',  #指定ipa最后输出的目录
    )
  pgyer(api_key: "ab0e08c84b7e6b06641219ac506dbe16", user_key: "208804b184ffa8e978b19e9752f3d8e8", password: "123456", install_type: "2")
end
end
